
server:
  port: 9090


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restapi
    username: tamer
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
#    properties:
#      hibernate:
